/**
 * [INPUT]: 依赖渠道、模板、草稿、参考图选择与生成回调
 * [OUTPUT]: 对外提供封面创作表单、规格预览与平台生成方案提示
 * [POS]: Cover Studio 的主编辑区；只收集意图并交由根组件持久化或发送 Agent
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
import { Sparkles } from "lucide-react";
import type { Channel, Draft, Template } from "./types";
import { ReferenceStrip } from "./asset-picker";
import { Button, Card } from "./ui";

export function CoverComposer({ channels, draft, templates, busy, onChange, onGenerate, onOpenReferences, onRemoveReference }: { channels: Channel[]; draft: Draft; templates: Template[]; busy: boolean; onChange: (next: Draft) => void; onGenerate: () => void; onOpenReferences: () => void; onRemoveReference: (id: string) => void }) {
  const selected = templates.find((item) => item.id === draft.templateId);
  const channel = channels.find((item) => item.id === draft.channel) ?? channels[0];
  const chooseChannel = (next: Channel) => onChange({ ...draft, channel: next.id, width: next.width, height: next.height });
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_17rem]"><Card className="overflow-hidden"><section className="p-5"><Section title="发布渠道与尺寸" detail="选择最终投放画布。" /><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{channels.map((item) => <button aria-pressed={item.id === channel.id} className={`rounded-lg border p-3 text-left transition ${item.id === channel.id ? "border-primary bg-primary/5 ring-1 ring-primary/30" : "hover:border-primary/45 hover:bg-muted/45"}`} key={item.id} onClick={() => chooseChannel(item)} type="button"><span className="block text-xs font-semibold">{item.label}</span><span className="mt-1 block font-mono text-[10px] text-muted-foreground">{item.width} × {item.height}</span></button>)}</div></section><section className="border-t p-5"><Section title="视觉模板" detail="模板决定基础提示词与构图语言。" /><div className="mt-3 grid gap-3 sm:grid-cols-3">{templates.map((template, index) => <button aria-pressed={template.id === selected?.id} className={`overflow-hidden rounded-lg border text-left transition ${template.id === selected?.id ? "border-primary ring-1 ring-primary/30" : "hover:border-primary/45"}`} key={template.id} onClick={() => onChange({ ...draft, templateId: template.id })} type="button"><span className={`block h-16 bg-gradient-to-br ${["from-emerald-950 via-emerald-700 to-amber-100", "from-amber-400 via-rose-500 to-violet-900", "from-teal-100 via-slate-500 to-rose-300"][index % 3]}`} /><span className="block p-3"><strong className="block text-xs">{template.name}</strong><span className="mt-1 block truncate text-[10px] text-muted-foreground">{template.prompt}</span></span></button>)}</div></section><section className="border-t p-5"><Section title="参考封面" detail="仅作视觉参考，始终保留原素材引用。" /><div className="mt-3"><ReferenceStrip ids={draft.referenceAssetIds} onOpen={onOpenReferences} onRemove={onRemoveReference} /></div></section><section className="border-t p-5"><Section title="补充要求" detail="和模板一起组成最终创作意图。" /><label className="mt-3 block text-xs font-medium" htmlFor="cover-brief">画面要求</label><textarea className="mt-2 block min-h-28 w-full rounded-lg border bg-background px-3 py-2.5 text-sm leading-6 outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20" id="cover-brief" onChange={(event) => onChange({ ...draft, brief: event.target.value })} placeholder="例如：主体放在右侧，左侧留出标题区域；整体克制、有科技杂志感。" value={draft.brief} /><div className="mt-4 flex items-center justify-between gap-4"><p className="max-w-xl text-xs leading-5 text-muted-foreground">{selected ? `将使用「${selected.name}」模板，${draft.referenceAssetIds.length ? `并参考 ${draft.referenceAssetIds.length} 张图片。` : "不附加参考图。"}` : "先选择一个视觉模板。"}</p><Button disabled={!selected || busy} onClick={onGenerate} type="button"><Sparkles className="size-3.5" />{busy ? "正在交给 Agent…" : "交给 Agent 生成"}</Button></div></section></Card><Specimen channel={channel} references={draft.referenceAssetIds.length} template={selected} /></div>;
}

function Section({ title, detail }: { title: string; detail: string }) { return <div className="flex items-baseline justify-between gap-4"><h2 className="text-sm font-semibold">{title}</h2><p className="text-[11px] text-muted-foreground">{detail}</p></div>; }
function Specimen({ channel, references, template }: { channel: Channel; references: number; template?: Template }) { return <Card className="h-fit p-4"><div className="mx-auto aspect-[3/4] max-w-52 overflow-hidden rounded-lg bg-[linear-gradient(145deg,#1e4838,#82b48c_50%,#f0dfbb_51%,#fcf7eb)] p-4"><div className="mt-7 ml-auto h-7 w-28 -rotate-[18deg] bg-amber-300" /><div className="mt-auto pt-36 text-3xl font-black leading-[.85] tracking-[-.1em] text-white">封面<br />预览</div></div><h2 className="mt-4 text-sm font-semibold">本次规格</h2><dl className="mt-3 grid grid-cols-[1fr_auto] gap-y-2 text-[11px]"><dt className="text-muted-foreground">渠道</dt><dd>{channel.label}</dd><dt className="text-muted-foreground">画布</dt><dd className="font-mono">{channel.width}×{channel.height}</dd><dt className="text-muted-foreground">模板</dt><dd className="max-w-28 truncate">{template?.name ?? "未选择"}</dd><dt className="text-muted-foreground">参考图</dt><dd>{references}</dd></dl><p className="mt-4 rounded-md bg-muted px-3 py-2 text-[11px] leading-4 text-muted-foreground">Agent 会先读取当前平台图片方案；最终必须以可引用 Asset 交付。</p></Card>; }
